name: "Reconfig Lab @ University of Manchester"
description: "This is the official web page for the Reconfig Lab at University of Manchester."

url: "https://reconfiglab.github.io/"

plugins: [jekyll-paginate]

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
